Caching disabled explicitly for extract.

Step extract has started.

Failed to run step extract.

Path.replace() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 230, in launch
    self._run_step(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 460, in _run_step
    self._run_step_without_step_operator(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 535, in _run_step_without_step_operator
    runner.run(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_runner.py", line 199, in run
    return_values = step_instance.call_entrypoint(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/steps/base_step.py", line 606, in call_entrypoint
    return self.entrypoint(**validated_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Sofa/Desktop/Innopolis/MLOps/ApartmentPrice/services/airflow/dags/data_prepare.py", line 24, in extract
    df, version = read_datastore()
                  ^^^^^^^^^^^^^^^^
  File "/Users/Sofa/Desktop/Innopolis/MLOps/ApartmentPrice/src/data.py", line 126, in read_datastore
    data_url = dvc.api.get_url(
               ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/dvc/api/data.py", line 84, in get_url
    index, entry = _repo.get_data_index_entry(path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/dvc/repo/__init__.py", line 382, in get_data_index_entry
    fs_path = self.dvcfs.from_os_path(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/dvc/fs/dvc.py", line 575, in from_os_path
    return as_posix(path)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/dvc/fs/dvc.py", line 30, in as_posix
    return path.replace(ntpath.sep, posixpath.sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Path.replace() takes 2 positional arguments but 3 were given

